"""empty message

Revision ID: 7fae027d4ef6
Revises: 77efb668245d
Create Date: 2017-05-22 14:13:11.674000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fae027d4ef6'
down_revision = '77efb668245d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_remove', sa.Boolean(), nullable=True))
    op.drop_column('post', 'is_movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_movie', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('post', 'is_remove')
    # ### end Alembic commands ###
