"""empty message

Revision ID: 8c418d9121c7
Revises: 7fae027d4ef6
Create Date: 2017-05-22 14:42:43.333000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c418d9121c7'
down_revision = '7fae027d4ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_removed', sa.Boolean(), nullable=True))
    op.drop_column('post', 'is_remove')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_remove', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('post', 'is_removed')
    # ### end Alembic commands ###
