"""empty message

Revision ID: 90b7b720940a
Revises: 24c7fcf2532c
Create Date: 2017-05-22 14:52:21.870000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b7b720940a'
down_revision = '24c7fcf2532c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_removed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_removed')
    # ### end Alembic commands ###
