"""empty message

Revision ID: 9307d08b8179
Revises: 696034b129b4
Create Date: 2017-05-23 15:42:30.988000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9307d08b8179'
down_revision = '696034b129b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('board_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('highlight_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'board', ['board_id'], ['id'])
    op.create_foreign_key(None, 'post', 'highlight', ['highlight_id'], ['id'])
    op.create_foreign_key(None, 'post', 'front_user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'highlight_id')
    op.drop_column('post', 'board_id')
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###
