"""empty message

Revision ID: a9de1720de6c
Revises: 793a51678240
Create Date: 2017-05-25 14:31:20.416000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9de1720de6c'
down_revision = '793a51678240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('old_last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'old_last_login')
    # ### end Alembic commands ###
