"""empty message

Revision ID: eaa9673bb0ff
Revises: a9de1720de6c
Create Date: 2017-05-26 11:41:54.223000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaa9673bb0ff'
down_revision = 'a9de1720de6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('avatar', sa.String(length=100), nullable=True))
    op.drop_column('front_user', 'avator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('avator', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('front_user', 'avatar')
    # ### end Alembic commands ###
